export const CoinManifest = [
	{
		symbol: '$PAC',
		name: 'PACcoin',
		color: '#f5eb16',
		'Image Path': '/$PAC.png',
	},
	{
		symbol: 'AAVE',
		name: 'AAVE',
		color: '#2ebac6',
		'Image Path': '/AAVE.png',
	},
	{
		symbol: 'ADA',
		name: 'Cardano',
		color: '#0d1e30',
		'Image Path': '/ADA.png',
	},
	{
		symbol: 'ADD',
		name: 'ADD Token',
		color: '#fec807',
		'Image Path': '/ADD.png',
	},
	{
		symbol: 'AE',
		name: 'Aeternity',
		color: '#de3f6b',
		'Image Path': '/AE.png',
	},
	{
		symbol: 'AEON',
		name: 'Aeon',
		color: '#134451',
		'Image Path': '/AEON.png',
	},
	{
		symbol: 'AGRS',
		name: 'Agoras Tauchain',
		color: '#f49e00',
		'Image Path': '/AGRS.png',
	},
	{
		symbol: 'AION',
		name: 'Aion',
		color: '#00bfec',
		'Image Path': '/AION.png',
	},
	{
		symbol: 'ALGO',
		name: 'Algorand',
		color: '#000000',
		'Image Path': '/ALGO.png',
	},
	{
		symbol: 'AMB',
		name: 'Ambrosus',
		color: '#3c5be0',
		'Image Path': '/AMB.png',
	},
	{
		symbol: 'AMP',
		name: 'HyperSpace (Synereo)',
		color: '#2daee4',
		'Image Path': '/AMP.png',
	},
	{
		symbol: 'AMPL',
		name: 'Ampleforth',
		color: '#000000',
		'Image Path': '/AMPL.png',
	},
	{
		symbol: 'ANKR',
		name: 'Ankr Network',
		color: '#2e6bf6',
		'Image Path': '/ANKR.png',
	},
	{
		symbol: 'ANT',
		name: 'Aragon',
		color: '#2cd3e1',
		'Image Path': '/ANT.png',
	},
	{
		symbol: 'ARG',
		name: 'Argentum',
		color: '#a71435',
		'Image Path': '/ARG.png',
	},
	{
		symbol: 'ARK',
		name: 'Ark',
		color: '#f70000',
		'Image Path': '/ARK.png',
	},
	{
		symbol: 'ARN',
		name: 'Aeron',
		color: '#0092b5',
		'Image Path': '/ARN.png',
	},
	{
		symbol: 'ARNX',
		name: 'Aeron',
		color: '#436697',
		'Image Path': '/ARNX.png',
	},
	{
		symbol: 'AST',
		name: 'AirSwap',
		color: '#0061ff',
		'Image Path': '/AST.png',
	},
	{
		symbol: 'ATM',
		name: 'ATMChain',
		color: '#346fce',
		'Image Path': '/ATM.png',
	},
	{
		symbol: 'ATOM',
		name: 'Cosmos',
		color: '#2e3148',
		'Image Path': '/ATOM.png',
	},
	{
		symbol: 'AUDR',
		name: 'AUDRamp',
		color: '#34318a',
		'Image Path': '/AUDR.png',
	},
	{
		symbol: 'AYWA',
		name: 'Aywa',
		color: '#3355b5',
		'Image Path': '/AYWA.png',
	},
	{
		symbol: 'BAL',
		name: 'Balancer',
		color: '#1e1e1e',
		'Image Path': '/BAL.png',
	},
	{
		symbol: 'BAND',
		name: 'Band Protocol',
		color: '#516aff',
		'Image Path': '/BAND.png',
	},
	{
		symbol: 'BCBC',
		name: 'BCBC',
		color: '#004ab5',
		'Image Path': '/BCBC.png',
	},
	{
		symbol: 'BCD',
		name: 'Bitcoin Diamond',
		color: '#fcc339',
		'Image Path': '/BCD.png',
	},
	{
		symbol: 'BCH',
		name: 'Bitcoin Cash',
		color: '#8dc351',
		'Image Path': '/BCH.png',
	},
	{
		symbol: 'BCIO',
		name: 'Blockchain.io',
		color: '#3f43ad',
		'Image Path': '/BCIO.png',
	},
	{
		symbol: 'BCN',
		name: 'Bytecoin',
		color: '#f04086',
		'Image Path': '/BCN.png',
	},
	{
		symbol: 'BCO',
		name: 'BananaCoin',
		color: '#2c76b7',
		'Image Path': '/BCO.png',
	},
	{
		symbol: 'BEAM',
		name: 'Beam',
		color: '#0b76ff',
		'Image Path': '/BEAM.png',
	},
	{
		symbol: 'BLZ',
		name: 'Blazecoin',
		color: '#18578c',
		'Image Path': '/BLZ.png',
	},
	{
		symbol: 'BOOTY',
		name: 'Booty',
		color: '#00b4f4',
		'Image Path': '/BOOTY.png',
	},
	{
		symbol: 'BPT',
		name: 'Blockport',
		color: '#0f63d8',
		'Image Path': '/BPT.png',
	},
	{
		symbol: 'BSV',
		name: 'BitcoinSV',
		color: '#eab304',
		'Image Path': '/BSV.png',
	},
	{
		symbol: 'BTCD',
		name: 'BitcoinDark',
		color: '#ff6600',
		'Image Path': '/BTCD.png',
	},
	{
		symbol: 'BTCH',
		name: 'Bitcoin Hush',
		color: '#4700c2',
		'Image Path': '/BTCH.png',
	},
	{
		symbol: 'BTCP',
		name: 'Bitcoin Private',
		color: '#272d63',
		'Image Path': '/BTCP.png',
	},
	{
		symbol: 'BTDX',
		name: 'Bitcloud',
		color: '#00aaff',
		'Image Path': '/BTDX.png',
	},
	{
		symbol: 'BTG',
		name: 'Bitcoin Gold',
		color: '#eba809',
		'Image Path': '/BTG.png',
	},
	{
		symbol: 'BTX',
		name: 'Bitcore',
		color: '#fb2ea3',
		'Image Path': '/BTX.png',
	},
	{
		symbol: 'BZE',
		name: 'BZEdge',
		color: '#00aeef',
		'Image Path': '/BZE.png',
	},
	{
		symbol: 'CALL',
		name: 'Capital',
		color: '#fbb413',
		'Image Path': '/CALL.png',
	},
	{
		symbol: 'CC',
		name: 'CoinCollect',
		color: '#36b0f3',
		'Image Path': '/CC.png',
	},
	{
		symbol: 'CDT',
		name: 'Blox',
		color: '#272731',
		'Image Path': '/CDT.png',
	},
	{
		symbol: 'CHAIN',
		name: 'Chainmakers',
		color: '#00aced',
		'Image Path': '/CHAIN.png',
	},
	{
		symbol: 'CHAT',
		name: 'ChatCoin',
		color: '#1c98f7',
		'Image Path': '/CHAT.png',
	},
	{
		symbol: 'CHIPS',
		name: 'CHIPS',
		color: '#598182',
		'Image Path': '/CHIPS.png',
	},
	{
		symbol: 'CHSB',
		name: 'SwissBorg',
		color: '#01c38d',
		'Image Path': '/CHSB.png',
	},
	{
		symbol: 'CLAM',
		name: 'Clams',
		color: '#20c5d3',
		'Image Path': '/CLAM.png',
	},
	{
		symbol: 'CLOAK',
		name: 'Cloakcoin',
		color: '#ff3a00',
		'Image Path': '/CLOAK.png',
	},
	{
		symbol: 'CNX',
		name: 'Cryptonex',
		color: '#4c6bae',
		'Image Path': '/CNX.png',
	},
	{
		symbol: 'COMP',
		name: 'Compound',
		color: '#00d395',
		'Image Path': '/COMP.png',
	},
	{
		symbol: 'COQUI',
		name: 'COQUI Cash',
		color: '#71c800',
		'Image Path': '/COQUI.png',
	},
	{
		symbol: 'CRPT',
		name: 'Crypterium',
		color: '#00bdcd',
		'Image Path': '/CRPT.png',
	},
	{
		symbol: 'CRV',
		name: 'Curve DAO Token',
		color: '#40649f',
		'Image Path': '/CRV.png',
	},
	{
		symbol: 'CRW',
		name: 'Crown',
		color: '#0f1529',
		'Image Path': '/CRW.png',
	},
	{
		symbol: 'DAI',
		name: 'Dai',
		color: '#f4b731',
		'Image Path': '/DAI.png',
	},
	{
		symbol: 'DATA',
		name: 'Streamr DATAcoin',
		color: '#e9570f',
		'Image Path': '/DATA.png',
	},
	{
		symbol: 'DCN',
		name: 'Dentacoin',
		color: '#136485',
		'Image Path': '/DCN.png',
	},
	{
		symbol: 'DNT',
		name: 'district0x',
		color: '#2c398f',
		'Image Path': '/DNT.png',
	},
	{
		symbol: 'DOT',
		name: 'Polkadot',
		color: '#e6007a',
		'Image Path': '/DOT.png',
	},
	{
		symbol: 'DRGN',
		name: 'Dragonchain',
		color: '#c91111',
		'Image Path': '/DRGN.png',
	},
	{
		symbol: 'DROP',
		name: 'Dropil',
		color: '#242d3d',
		'Image Path': '/DROP.png',
	},
	{
		symbol: 'DTH',
		name: 'Dether',
		color: '#3c80f1',
		'Image Path': '/DTH.png',
	},
	{
		symbol: 'ECA',
		name: 'Electra',
		color: '#aa15dd',
		'Image Path': '/ECA.png',
	},
	{
		symbol: 'EDG',
		name: 'Edgeless',
		color: '#2b1544',
		'Image Path': '/EDG.png',
	},
	{
		symbol: 'ELF',
		name: 'aelf',
		color: '#2b5ebb',
		'Image Path': '/ELF.png',
	},
	{
		symbol: 'ELIX',
		name: 'Elixir',
		color: '#00aded',
		'Image Path': '/ELIX.png',
	},
	{
		symbol: 'EMB',
		name: 'Emblem',
		color: '#f6c054',
		'Image Path': '/EMB.png',
	},
	{
		symbol: 'ENTRP',
		name: 'Hut34 Entropy',
		color: '#fa5836',
		'Image Path': '/ENTRP.png',
	},
	{
		symbol: 'EON',
		name: 'EOS Network',
		color: '#443f54',
		'Image Path': '/EON.png',
	},
	{
		symbol: 'EOP',
		name: 'EOP',
		color: '#35a7df',
		'Image Path': '/EOP.png',
	},
	{
		symbol: 'ETC',
		name: 'Ethereum Classic',
		color: '#328332',
		'Image Path': '/ETC.png',
	},
	{
		symbol: 'ETH',
		name: 'Ethereum',
		color: '#627eea',
		'Image Path': '/ETH.png',
	},
	{
		symbol: 'ETHOS',
		name: 'Ethos',
		color: '#00ffba',
		'Image Path': '/ETHOS.png',
	},
	{
		symbol: 'ETN',
		name: 'Electroneum',
		color: '#23bee2',
		'Image Path': '/ETN.png',
	},
	{
		symbol: 'ETP',
		name: 'Metaverse ETP',
		color: '#00a5ff',
		'Image Path': '/ETP.png',
	},
	{
		symbol: 'FCT',
		name: 'Factom',
		color: '#417ba4',
		'Image Path': '/FCT.png',
	},
	{
		symbol: 'FJC',
		name: 'Fujicoin',
		color: '#00afec',
		'Image Path': '/FJC.png',
	},
	{
		symbol: 'FLDC',
		name: 'Foldingcoin',
		color: '#c40e09',
		'Image Path': '/FLDC.png',
	},
	{
		symbol: 'FLO',
		name: 'FLO',
		color: '#2080a2',
		'Image Path': '/FLO.png',
	},
	{
		symbol: 'FLUX',
		name: 'Flux',
		color: '#2b61d1',
		'Image Path': '/FLUX.png',
	},
	{
		symbol: 'FSN',
		name: 'FUSION',
		color: '#1d9ad7',
		'Image Path': '/FSN.png',
	},
	{
		symbol: 'FTC',
		name: 'Feathercoin',
		color: '#27323a',
		'Image Path': '/FTC.png',
	},
	{
		symbol: 'FUN',
		name: 'FunFair',
		color: '#ed1968',
		'Image Path': '/FUN.png',
	},
	{
		symbol: 'GIN',
		name: 'GINcoin',
		color: '#008dde',
		'Image Path': '/GIN.png',
	},
	{
		symbol: 'GLXT',
		name: 'GLX Token',
		color: '#005396',
		'Image Path': '/GLXT.png',
	},
	{
		symbol: 'GMR',
		name: 'Gimmer',
		color: '#372d2c',
		'Image Path': '/GMR.png',
	},
	{
		symbol: 'GNO',
		name: 'Gnosis',
		color: '#00a6c4',
		'Image Path': '/GNO.png',
	},
	{
		symbol: 'GRC',
		name: 'Gridcoin',
		color: '#5411b3',
		'Image Path': '/GRC.png',
	},
	{
		symbol: 'GRIN',
		name: 'Grin',
		color: '#fff300',
		'Image Path': '/GRIN.png',
	},
	{
		symbol: 'GRS',
		name: 'Groestlcoin',
		color: '#377e96',
		'Image Path': '/GRS.png',
	},
	{
		symbol: 'GRT',
		name: 'The Graph',
		color: '#5942cc',
		'Image Path': '/GRT.png',
	},
	{
		symbol: 'GSC',
		name: 'Global Social Chain',
		color: '#ff0060',
		'Image Path': '/GSC.png',
	},
	{
		symbol: 'HIGHT',
		name: 'Highcoin',
		color: '#117fc0',
		'Image Path': '/HIGHT.png',
	},
	{
		symbol: 'HNS',
		name: 'Handshake',
		color: '#000000',
		'Image Path': '/HNS.png',
	},
	{
		symbol: 'HPB',
		name: 'High Performance Blockchain',
		color: '#1591ca',
		'Image Path': '/HPB.png',
	},
	{
		symbol: 'HUSD',
		name: 'HUSD',
		color: '#005ffa',
		'Image Path': '/HUSD.png',
	},
	{
		symbol: 'ICP',
		name: 'Internet Computer',
		color: '#292a2e',
		'Image Path': '/ICP.png',
	},
	{
		symbol: 'ILK',
		name: 'Inlock Token',
		color: '#98c23a',
		'Image Path': '/ILK.png',
	},
	{
		symbol: 'IOTX',
		name: 'IoTeX',
		color: '#00d4d5',
		'Image Path': '/IOTX.png',
	},
	{
		symbol: 'ITC',
		name: 'IoT Chain',
		color: '#102044',
		'Image Path': '/ITC.png',
	},
	{
		symbol: 'KIN',
		name: 'Kin',
		color: '#005fff',
		'Image Path': '/KIN.png',
	},
	{
		symbol: 'KLOWN',
		name: 'Ether Clown',
		color: '#ea0017',
		'Image Path': '/KLOWN.png',
	},
	{
		symbol: 'KNC',
		name: 'Kyber Network',
		color: '#31cb9e',
		'Image Path': '/KNC.png',
	},
	{
		symbol: 'KSM',
		name: 'Kusama',
		color: '#000000',
		'Image Path': '/KSM.png',
	},
	{
		symbol: 'LBC',
		name: 'LBRY Credits',
		color: '#006149',
		'Image Path': '/LBC.png',
	},
	{
		symbol: 'LEO',
		name: 'Unus Sed LEO',
		color: '#11021e',
		'Image Path': '/LEO.png',
	},
	{
		symbol: 'LINK',
		name: 'ChainLink',
		color: '#2a5ada',
		'Image Path': '/LINK.png',
	},
	{
		symbol: 'LOOM',
		name: 'Loom Network',
		color: '#48beff',
		'Image Path': '/LOOM.png',
	},
	{
		symbol: 'LSK',
		name: 'Lisk',
		color: '#0d4ea0',
		'Image Path': '/LSK.png',
	},
	{
		symbol: 'LUN',
		name: 'Lunyr',
		color: '#f55749',
		'Image Path': '/LUN.png',
	},
	{
		symbol: 'MAID',
		name: 'MaidSafeCoin',
		color: '#5592d7',
		'Image Path': '/MAID.png',
	},
	{
		symbol: 'MANA',
		name: 'Decentraland',
		color: '#ff2d55',
		'Image Path': '/MANA.png',
	},
	{
		symbol: 'MATIC',
		name: 'Polygon',
		color: '#6f41d8',
		'Image Path': '/MATIC.png',
	},
	{
		symbol: 'MATIC',
		name: 'Polygon',
		color: '#6f41d8',
		'Image Path': '/MATIC.png',
	},
	{
		symbol: 'MAX',
		name: 'MAX Token',
		color: '#2d4692',
		'Image Path': '/MAX.png',
	},
	{
		symbol: 'MCO',
		name: 'Crypto.com',
		color: '#103f68',
		'Image Path': '/MCO.png',
	},
	{
		symbol: 'MFT',
		name: 'Mainframe',
		color: '#da1157',
		'Image Path': '/MFT.png',
	},
	{
		symbol: 'MITH',
		name: 'Mithril',
		color: '#00316d',
		'Image Path': '/MITH.png',
	},
	{
		symbol: 'MKR',
		name: 'Maker',
		color: '#1aab9b',
		'Image Path': '/MKR.png',
	},
	{
		symbol: 'MNZ',
		name: 'MNZ',
		color: '#7f368a',
		'Image Path': '/MNZ.png',
	},
	{
		symbol: 'MSR',
		name: 'Masari',
		color: '#47b95c',
		'Image Path': '/MSR.png',
	},
	{
		symbol: 'MTH',
		name: 'Monetha',
		color: '#104fca',
		'Image Path': '/MTH.png',
	},
	{
		symbol: 'MUSIC',
		name: 'Musicoin',
		color: '#ffffff',
		'Image Path': '/MUSIC.png',
	},
	{
		symbol: 'MZC',
		name: 'MAZA',
		color: '#ffaa05',
		'Image Path': '/MZC.png',
	},
	{
		symbol: 'NCASH',
		name: 'Nucleus Vision',
		color: '#36a9cf',
		'Image Path': '/NCASH.png',
	},
	{
		symbol: 'NEU',
		name: 'Neumark',
		color: '#b3ba00',
		'Image Path': '/NEU.png',
	},
	{
		symbol: 'NEXO',
		name: 'Nexo',
		color: '#1a4199',
		'Image Path': '/NEXO.png',
	},
	{
		symbol: 'NKN',
		name: 'NKN',
		color: '#23336f',
		'Image Path': '/NKN.png',
	},
	{
		symbol: 'NLC2',
		name: 'NoLimitCoin',
		color: '#f28f01',
		'Image Path': '/NLC2.png',
	},
	{
		symbol: 'NMR',
		name: 'Numeraire',
		color: '#050708',
		'Image Path': '/NMR.png',
	},
	{
		symbol: 'NPXS',
		name: 'Pundi X',
		color: '#f5d100',
		'Image Path': '/NPXS.png',
	},
	{
		symbol: 'NTBC',
		name: 'Note Blockchain',
		color: '#eec315',
		'Image Path': '/NTBC.png',
	},
	{
		symbol: 'NXS',
		name: 'Nexus',
		color: '#4099cd',
		'Image Path': '/NXS.png',
	},
	{
		symbol: 'OAX',
		name: 'OpenANX',
		color: '#164b79',
		'Image Path': '/OAX.png',
	},
	{
		symbol: 'OMG',
		name: 'OMG Network',
		color: '#101010',
		'Image Path': '/OMG.png',
	},
	{
		symbol: 'ONE',
		name: 'Harmony',
		color: '#00aee9',
		'Image Path': '/ONE.png',
	},
	{
		symbol: 'OOT',
		name: 'Utrum',
		color: '#25aae1',
		'Image Path': '/OOT.png',
	},
	{
		symbol: 'OXT',
		name: 'Orchid',
		color: '#5f45ba',
		'Image Path': '/OXT.png',
	},
	{
		symbol: 'PART',
		name: 'Particl',
		color: '#65cb8d',
		'Image Path': '/PART.png',
	},
	{
		symbol: 'PAX',
		name: 'PAX Token',
		color: '#398260',
		'Image Path': '/PAX.png',
	},
	{
		symbol: 'PAXG',
		name: 'PAX Gold',
		color: '#e4ce4d',
		'Image Path': '/PAXG.png',
	},
	{
		symbol: 'PAY',
		name: 'TenX',
		color: '#302c2c',
		'Image Path': '/PAY.png',
	},
	{
		symbol: 'POWR',
		name: 'Power Ledger',
		color: '#05bca9',
		'Image Path': '/POWR.png',
	},
	{
		symbol: 'PPP',
		name: 'PayPie',
		color: '#348f8d',
		'Image Path': '/PPP.png',
	},
	{
		symbol: 'PRL',
		name: 'Oyster',
		color: '#1061e3',
		'Image Path': '/PRL.png',
	},
	{
		symbol: 'PUNGO',
		name: 'Pungo Token',
		color: '#22b573',
		'Image Path': '/PUNGO.png',
	},
	{
		symbol: 'QASH',
		name: 'QASH',
		color: '#1347e8',
		'Image Path': '/QASH.png',
	},
	{
		symbol: 'QIWI',
		name: 'QIWI',
		color: '#ff8c00',
		'Image Path': '/QIWI.png',
	},
	{
		symbol: 'QLC',
		name: 'QLC Chain',
		color: '#610089',
		'Image Path': '/QLC.png',
	},
	{
		symbol: 'QTUM',
		name: 'Qtum',
		color: '#2e9ad0',
		'Image Path': '/QTUM.png',
	},
	{
		symbol: 'RCN',
		name: 'Rcoin',
		color: '#3555f9',
		'Image Path': '/RCN.png',
	},
	{
		symbol: 'RDD',
		name: 'Reddcoin',
		color: '#e30613',
		'Image Path': '/RDD.png',
	},
	{
		symbol: 'REN',
		name: 'Ren',
		color: '#080817',
		'Image Path': '/REN.png',
	},
	{
		symbol: 'REP',
		name: 'Augur',
		color: '#602a52',
		'Image Path': '/REP.png',
	},
	{
		symbol: 'REPV2',
		name: 'Augur',
		color: '#0e0e21',
		'Image Path': '/REPV2.png',
	},
	{
		symbol: 'REQ',
		name: 'Request',
		color: '#00e6a0',
		'Image Path': '/REQ.png',
	},
	{
		symbol: 'RLC',
		name: 'iExec RLC',
		color: '#ffd800',
		'Image Path': '/RLC.png',
	},
	{
		symbol: 'RPX',
		name: 'RPX',
		color: '#8d181b',
		'Image Path': '/RPX.png',
	},
	{
		symbol: 'RVN',
		name: 'Ravencoin',
		color: '#384182',
		'Image Path': '/RVN.png',
	},
	{
		symbol: 'SAFE',
		name: 'Safe',
		color: '#00688c',
		'Image Path': '/SAFE.png',
	},
	{
		symbol: 'SAFEMOON',
		name: 'SafeMoon',
		color: '#00a79d',
		'Image Path': '/SAFEMOON.png',
	},
	{
		symbol: 'SAI',
		name: 'Single Collateral DAI',
		color: '#b68900',
		'Image Path': '/SAI.png',
	},
	{
		symbol: 'SAN',
		name: 'Santiment Network Token',
		color: '#2b77b3',
		'Image Path': '/SAN.png',
	},
	{
		symbol: 'SAND',
		name: 'The Sandbox',
		color: '#04adef',
		'Image Path': '/SAND.png',
	},
	{
		symbol: 'SBERBANK',
		name: 'SBERBANK',
		color: '#48b254',
		'Image Path': '/SBERBANK.png',
	},
	{
		symbol: 'SIN',
		name: 'SINOVATE',
		color: '#f5342e',
		'Image Path': '/SIN.png',
	},
	{
		symbol: 'SKL',
		name: 'SKALE Network',
		color: '#000000',
		'Image Path': '/SKL.png',
	},
	{
		symbol: 'SKY',
		name: 'Skycoin',
		color: '#0072ff',
		'Image Path': '/SKY.png',
	},
	{
		symbol: 'SLR',
		name: 'Solarcoin',
		color: '#fda616',
		'Image Path': '/SLR.png',
	},
	{
		symbol: 'SNGLS',
		name: 'SingularDTV',
		color: '#b30d23',
		'Image Path': '/SNGLS.png',
	},
	{
		symbol: 'SNM',
		name: 'SONM',
		color: '#0b1c26',
		'Image Path': '/SNM.png',
	},
	{
		symbol: 'SNX',
		name: 'Synthetix',
		color: '#5fcdf9',
		'Image Path': '/SNX.png',
	},
	{
		symbol: 'SOC',
		name: 'All Sports',
		color: '#199248',
		'Image Path': '/SOC.png',
	},
	{
		symbol: 'SOL',
		name: 'Solana',
		color: '#66f9a1',
		'Image Path': '/SOL.png',
	},
	{
		symbol: 'SPACEHBIT',
		name: 'HashBit Blockchain',
		color: '#0971fe',
		'Image Path': '/SPACEHBIT.png',
	},
	{
		symbol: 'SPANK',
		name: 'SpankChain',
		color: '#ff3b81',
		'Image Path': '/SPANK.png',
	},
	{
		symbol: 'SPHTX',
		name: 'SophiaTX',
		color: '#00b098',
		'Image Path': '/SPHTX.png',
	},
	{
		symbol: 'STORJ',
		name: 'Storj',
		color: '#2683ff',
		'Image Path': '/STORJ.png',
	},
	{
		symbol: 'STOX',
		name: 'Stox',
		color: '#7324f0',
		'Image Path': '/STOX.png',
	},
	{
		symbol: 'STRAT',
		name: 'Stratis',
		color: '#1387c9',
		'Image Path': '/STRAT.png',
	},
	{
		symbol: 'STX',
		name: 'Stacks',
		color: '#5546ff',
		'Image Path': '/STX.png',
	},
	{
		symbol: 'SUSHI',
		name: 'SushiSwap',
		color: '#d65892',
		'Image Path': '/SUSHI.png',
	},
	{
		symbol: 'SYS',
		name: 'Syscoin',
		color: '#0082c6',
		'Image Path': '/SYS.png',
	},
	{
		symbol: 'TBX',
		name: 'Tokenbox',
		color: '#5244d4',
		'Image Path': '/TBX.png',
	},
	{
		symbol: 'TEN',
		name: 'Tokenomy',
		color: '#0899cd',
		'Image Path': '/TEN.png',
	},
	{
		symbol: 'TGCH',
		name: 'TrueGalaxyCash',
		color: '#434247',
		'Image Path': '/TGCH.png',
	},
	{
		symbol: 'TKS',
		name: 'Tokes Platform',
		color: '#895af8',
		'Image Path': '/TKS.png',
	},
	{
		symbol: 'TOMO',
		name: 'TomoChain',
		color: '#1a1f36',
		'Image Path': '/TOMO.png',
	},
	{
		symbol: 'TPAY',
		name: 'TokenPay',
		color: '#3058a6',
		'Image Path': '/TPAY.png',
	},
	{
		symbol: 'TRIG',
		name: 'Triggers',
		color: '#30c0f2',
		'Image Path': '/TRIG.png',
	},
	{
		symbol: 'TRTL',
		name: 'TurtleCoin',
		color: '#00843d',
		'Image Path': '/TRTL.png',
	},
	{
		symbol: 'TRX',
		name: 'TRON',
		color: '#ef0027',
		'Image Path': '/TRX.png',
	},
	{
		symbol: 'TUSD',
		name: 'TrueUSD',
		color: '#2b2e7f',
		'Image Path': '/TUSD.png',
	},
	{
		symbol: 'UBQ',
		name: 'Ubiq',
		color: '#00ea90',
		'Image Path': '/UBQ.png',
	},
	{
		symbol: 'UMA',
		name: 'UMA',
		color: '#ff4a4a',
		'Image Path': '/UMA.png',
	},
	{
		symbol: 'UNI',
		name: 'Uniswap',
		color: '#ff007a',
		'Image Path': '/UNI.png',
	},
	{
		symbol: 'USDC',
		name: 'USD Coin',
		color: '#3e73c4',
		'Image Path': '/USDC.png',
	},
	{
		symbol: 'VIBE',
		name: 'VIBE',
		color: '#338be5',
		'Image Path': '/VIBE.png',
	},
	{
		symbol: 'VRSC',
		name: 'VerusCoin',
		color: '#3165d4',
		'Image Path': '/VRSC.png',
	},
	{
		symbol: 'VRSC',
		name: 'VerusCoin',
		color: '#3165d4',
		'Image Path': '/VRSC.png',
	},
	{
		symbol: 'VTC',
		name: 'Vertcoin',
		color: '#048657',
		'Image Path': '/VTC.png',
	},
	{
		symbol: 'WABI',
		name: 'Tael',
		color: '#399b32',
		'Image Path': '/WABI.png',
	},
	{
		symbol: 'WAN',
		name: 'Wanchain',
		color: '#136aad',
		'Image Path': '/WAN.png',
	},
	{
		symbol: 'WBTC',
		name: 'Wrapped Bitcoin',
		color: '#201a2d',
		'Image Path': '/WBTC.png',
	},
	{
		symbol: 'WICC',
		name: 'WaykiChain',
		color: '#5783cb',
		'Image Path': '/WICC.png',
	},
	{
		symbol: 'WINGS',
		name: 'Wings',
		color: '#0dc9f7',
		'Image Path': '/WINGS.png',
	},
	{
		symbol: 'WPR',
		name: 'WePower',
		color: '#ffe600',
		'Image Path': '/WPR.png',
	},
	{
		symbol: 'XAS',
		name: 'Asch',
		color: '#faa00d',
		'Image Path': '/XAS.png',
	},
	{
		symbol: 'XBC',
		name: 'Bitcoin Plus',
		color: '#f7931a',
		'Image Path': '/XBC.png',
	},
	{
		symbol: 'XBP',
		name: 'BlitzPredict',
		color: '#21af67',
		'Image Path': '/XBP.png',
	},
	{
		symbol: 'XMCC',
		name: 'Monoeci',
		color: '#dd0632',
		'Image Path': '/XMCC.png',
	},
	{
		symbol: 'XP',
		name: 'XP',
		color: '#008200',
		'Image Path': '/XP.png',
	},
	{
		symbol: 'XPR',
		name: 'Proton',
		color: '#7543e3',
		'Image Path': '/XPR.png',
	},
	{
		symbol: 'XSG',
		name: 'SnowGem',
		color: '#d21e2b',
		'Image Path': '/XSG.png',
	},
	{
		symbol: 'XVG',
		name: 'Verge',
		color: '#00cbff',
		'Image Path': '/XVG.png',
	},
	{
		symbol: 'YFI',
		name: 'yearn.finance',
		color: '#006ae3',
		'Image Path': '/YFI.png',
	},
	{
		symbol: 'ZCL',
		name: 'Zclassic',
		color: '#c87035',
		'Image Path': '/ZCL.png',
	},
	{
		symbol: 'ZEN',
		name: 'Horizen',
		color: '#00eaab',
		'Image Path': '/ZEN.png',
	},
	{
		symbol: 'ZEST',
		name: 'Zest',
		color: '#07bc9c',
		'Image Path': '/ZEST.png',
	},
	{
		symbol: 'ZEST',
		name: 'Zest',
		color: '#07bc9c',
		'Image Path': '/ZEST.png',
	},
	{
		symbol: 'ZILLA',
		name: 'Chainzilla',
		color: '#00004d',
		'Image Path': '/ZILLA.png',
	},
	{
		symbol: 'ZRX',
		name: '0x',
		color: '#302c2c',
		'Image Path': '/ZRX.png',
	},
];
