export const CoinManifest = [
	{
		symbol: '$PAC',
		name: 'PACcoin',
		color: '#f5eb16',
		'Image Path': '/FormattedImages/$PAC.png',
	},
	{
		symbol: 'AAVE',
		name: 'AAVE',
		color: '#2ebac6',
		'Image Path': '/FormattedImages/AAVE.png',
	},
	{
		symbol: 'ADA',
		name: 'Cardano',
		color: '#0d1e30',
		'Image Path': '/FormattedImages/ADA.png',
	},
	{
		symbol: 'ADD',
		name: 'ADD Token',
		color: '#fec807',
		'Image Path': '/FormattedImages/ADD.png',
	},
	{
		symbol: 'AE',
		name: 'Aeternity',
		color: '#de3f6b',
		'Image Path': '/FormattedImages/AE.png',
	},
	{
		symbol: 'AEON',
		name: 'Aeon',
		color: '#134451',
		'Image Path': '/FormattedImages/AEON.png',
	},
	{
		symbol: 'AGRS',
		name: 'Agoras Tauchain',
		color: '#f49e00',
		'Image Path': '/FormattedImages/AGRS.png',
	},
	{
		symbol: 'AION',
		name: 'Aion',
		color: '#00bfec',
		'Image Path': '/FormattedImages/AION.png',
	},
	{
		symbol: 'ALGO',
		name: 'Algorand',
		color: '#000000',
		'Image Path': '/FormattedImages/ALGO.png',
	},
	{
		symbol: 'AMB',
		name: 'Ambrosus',
		color: '#3c5be0',
		'Image Path': '/FormattedImages/AMB.png',
	},
	{
		symbol: 'AMP',
		name: 'HyperSpace (Synereo)',
		color: '#2daee4',
		'Image Path': '/FormattedImages/AMP.png',
	},
	{
		symbol: 'AMPL',
		name: 'Ampleforth',
		color: '#000000',
		'Image Path': '/FormattedImages/AMPL.png',
	},
	{
		symbol: 'ANKR',
		name: 'Ankr Network',
		color: '#2e6bf6',
		'Image Path': '/FormattedImages/ANKR.png',
	},
	{
		symbol: 'ANT',
		name: 'Aragon',
		color: '#2cd3e1',
		'Image Path': '/FormattedImages/ANT.png',
	},
	{
		symbol: 'ARG',
		name: 'Argentum',
		color: '#a71435',
		'Image Path': '/FormattedImages/ARG.png',
	},
	{
		symbol: 'ARK',
		name: 'Ark',
		color: '#f70000',
		'Image Path': '/FormattedImages/ARK.png',
	},
	{
		symbol: 'ARN',
		name: 'Aeron',
		color: '#0092b5',
		'Image Path': '/FormattedImages/ARN.png',
	},
	{
		symbol: 'ARNX',
		name: 'Aeron',
		color: '#436697',
		'Image Path': '/FormattedImages/ARNX.png',
	},
	{
		symbol: 'AST',
		name: 'AirSwap',
		color: '#0061ff',
		'Image Path': '/FormattedImages/AST.png',
	},
	{
		symbol: 'ATM',
		name: 'ATMChain',
		color: '#346fce',
		'Image Path': '/FormattedImages/ATM.png',
	},
	{
		symbol: 'ATOM',
		name: 'Cosmos',
		color: '#2e3148',
		'Image Path': '/FormattedImages/ATOM.png',
	},
	{
		symbol: 'AUDR',
		name: 'AUDRamp',
		color: '#34318a',
		'Image Path': '/FormattedImages/AUDR.png',
	},
	{
		symbol: 'AYWA',
		name: 'Aywa',
		color: '#3355b5',
		'Image Path': '/FormattedImages/AYWA.png',
	},
	{
		symbol: 'BAL',
		name: 'Balancer',
		color: '#1e1e1e',
		'Image Path': '/FormattedImages/BAL.png',
	},
	{
		symbol: 'BAND',
		name: 'Band Protocol',
		color: '#516aff',
		'Image Path': '/FormattedImages/BAND.png',
	},
	{
		symbol: 'BCBC',
		name: 'BCBC',
		color: '#004ab5',
		'Image Path': '/FormattedImages/BCBC.png',
	},
	{
		symbol: 'BCD',
		name: 'Bitcoin Diamond',
		color: '#fcc339',
		'Image Path': '/FormattedImages/BCD.png',
	},
	{
		symbol: 'BCH',
		name: 'Bitcoin Cash',
		color: '#8dc351',
		'Image Path': '/FormattedImages/BCH.png',
	},
	{
		symbol: 'BCIO',
		name: 'Blockchain.io',
		color: '#3f43ad',
		'Image Path': '/FormattedImages/BCIO.png',
	},
	{
		symbol: 'BCN',
		name: 'Bytecoin',
		color: '#f04086',
		'Image Path': '/FormattedImages/BCN.png',
	},
	{
		symbol: 'BCO',
		name: 'BananaCoin',
		color: '#2c76b7',
		'Image Path': '/FormattedImages/BCO.png',
	},
	{
		symbol: 'BEAM',
		name: 'Beam',
		color: '#0b76ff',
		'Image Path': '/FormattedImages/BEAM.png',
	},
	{
		symbol: 'BLZ',
		name: 'Blazecoin',
		color: '#18578c',
		'Image Path': '/FormattedImages/BLZ.png',
	},
	{
		symbol: 'BOOTY',
		name: 'Booty',
		color: '#00b4f4',
		'Image Path': '/FormattedImages/BOOTY.png',
	},
	{
		symbol: 'BPT',
		name: 'Blockport',
		color: '#0f63d8',
		'Image Path': '/FormattedImages/BPT.png',
	},
	{
		symbol: 'BSV',
		name: 'BitcoinSV',
		color: '#eab304',
		'Image Path': '/FormattedImages/BSV.png',
	},
	{
		symbol: 'BTCD',
		name: 'BitcoinDark',
		color: '#ff6600',
		'Image Path': '/FormattedImages/BTCD.png',
	},
	{
		symbol: 'BTCH',
		name: 'Bitcoin Hush',
		color: '#4700c2',
		'Image Path': '/FormattedImages/BTCH.png',
	},
	{
		symbol: 'BTCP',
		name: 'Bitcoin Private',
		color: '#272d63',
		'Image Path': '/FormattedImages/BTCP.png',
	},
	{
		symbol: 'BTDX',
		name: 'Bitcloud',
		color: '#00aaff',
		'Image Path': '/FormattedImages/BTDX.png',
	},
	{
		symbol: 'BTG',
		name: 'Bitcoin Gold',
		color: '#eba809',
		'Image Path': '/FormattedImages/BTG.png',
	},
	{
		symbol: 'BTX',
		name: 'Bitcore',
		color: '#fb2ea3',
		'Image Path': '/FormattedImages/BTX.png',
	},
	{
		symbol: 'BZE',
		name: 'BZEdge',
		color: '#00aeef',
		'Image Path': '/FormattedImages/BZE.png',
	},
	{
		symbol: 'CALL',
		name: 'Capital',
		color: '#fbb413',
		'Image Path': '/FormattedImages/CALL.png',
	},
	{
		symbol: 'CC',
		name: 'CoinCollect',
		color: '#36b0f3',
		'Image Path': '/FormattedImages/CC.png',
	},
	{
		symbol: 'CDT',
		name: 'Blox',
		color: '#272731',
		'Image Path': '/FormattedImages/CDT.png',
	},
	{
		symbol: 'CHAIN',
		name: 'Chainmakers',
		color: '#00aced',
		'Image Path': '/FormattedImages/CHAIN.png',
	},
	{
		symbol: 'CHAT',
		name: 'ChatCoin',
		color: '#1c98f7',
		'Image Path': '/FormattedImages/CHAT.png',
	},
	{
		symbol: 'CHIPS',
		name: 'CHIPS',
		color: '#598182',
		'Image Path': '/FormattedImages/CHIPS.png',
	},
	{
		symbol: 'CHSB',
		name: 'SwissBorg',
		color: '#01c38d',
		'Image Path': '/FormattedImages/CHSB.png',
	},
	{
		symbol: 'CLAM',
		name: 'Clams',
		color: '#20c5d3',
		'Image Path': '/FormattedImages/CLAM.png',
	},
	{
		symbol: 'CLOAK',
		name: 'Cloakcoin',
		color: '#ff3a00',
		'Image Path': '/FormattedImages/CLOAK.png',
	},
	{
		symbol: 'CNX',
		name: 'Cryptonex',
		color: '#4c6bae',
		'Image Path': '/FormattedImages/CNX.png',
	},
	{
		symbol: 'COMP',
		name: 'Compound',
		color: '#00d395',
		'Image Path': '/FormattedImages/COMP.png',
	},
	{
		symbol: 'COQUI',
		name: 'COQUI Cash',
		color: '#71c800',
		'Image Path': '/FormattedImages/COQUI.png',
	},
	{
		symbol: 'CRPT',
		name: 'Crypterium',
		color: '#00bdcd',
		'Image Path': '/FormattedImages/CRPT.png',
	},
	{
		symbol: 'CRV',
		name: 'Curve DAO Token',
		color: '#40649f',
		'Image Path': '/FormattedImages/CRV.png',
	},
	{
		symbol: 'CRW',
		name: 'Crown',
		color: '#0f1529',
		'Image Path': '/FormattedImages/CRW.png',
	},
	{
		symbol: 'DAI',
		name: 'Dai',
		color: '#f4b731',
		'Image Path': '/FormattedImages/DAI.png',
	},
	{
		symbol: 'DATA',
		name: 'Streamr DATAcoin',
		color: '#e9570f',
		'Image Path': '/FormattedImages/DATA.png',
	},
	{
		symbol: 'DCN',
		name: 'Dentacoin',
		color: '#136485',
		'Image Path': '/FormattedImages/DCN.png',
	},
	{
		symbol: 'DNT',
		name: 'district0x',
		color: '#2c398f',
		'Image Path': '/FormattedImages/DNT.png',
	},
	{
		symbol: 'DOT',
		name: 'Polkadot',
		color: '#e6007a',
		'Image Path': '/FormattedImages/DOT.png',
	},
	{
		symbol: 'DRGN',
		name: 'Dragonchain',
		color: '#c91111',
		'Image Path': '/FormattedImages/DRGN.png',
	},
	{
		symbol: 'DROP',
		name: 'Dropil',
		color: '#242d3d',
		'Image Path': '/FormattedImages/DROP.png',
	},
	{
		symbol: 'DTH',
		name: 'Dether',
		color: '#3c80f1',
		'Image Path': '/FormattedImages/DTH.png',
	},
	{
		symbol: 'ECA',
		name: 'Electra',
		color: '#aa15dd',
		'Image Path': '/FormattedImages/ECA.png',
	},
	{
		symbol: 'EDG',
		name: 'Edgeless',
		color: '#2b1544',
		'Image Path': '/FormattedImages/EDG.png',
	},
	{
		symbol: 'ELF',
		name: 'aelf',
		color: '#2b5ebb',
		'Image Path': '/FormattedImages/ELF.png',
	},
	{
		symbol: 'ELIX',
		name: 'Elixir',
		color: '#00aded',
		'Image Path': '/FormattedImages/ELIX.png',
	},
	{
		symbol: 'EMB',
		name: 'Emblem',
		color: '#f6c054',
		'Image Path': '/FormattedImages/EMB.png',
	},
	{
		symbol: 'ENTRP',
		name: 'Hut34 Entropy',
		color: '#fa5836',
		'Image Path': '/FormattedImages/ENTRP.png',
	},
	{
		symbol: 'EON',
		name: 'EOS Network',
		color: '#443f54',
		'Image Path': '/FormattedImages/EON.png',
	},
	{
		symbol: 'EOP',
		name: 'EOP',
		color: '#35a7df',
		'Image Path': '/FormattedImages/EOP.png',
	},
	{
		symbol: 'ETC',
		name: 'Ethereum Classic',
		color: '#328332',
		'Image Path': '/FormattedImages/ETC.png',
	},
	{
		symbol: 'ETH',
		name: 'Ethereum',
		color: '#627eea',
		'Image Path': '/FormattedImages/ETH.png',
	},
	{
		symbol: 'ETHOS',
		name: 'Ethos',
		color: '#00ffba',
		'Image Path': '/FormattedImages/ETHOS.png',
	},
	{
		symbol: 'ETN',
		name: 'Electroneum',
		color: '#23bee2',
		'Image Path': '/FormattedImages/ETN.png',
	},
	{
		symbol: 'ETP',
		name: 'Metaverse ETP',
		color: '#00a5ff',
		'Image Path': '/FormattedImages/ETP.png',
	},
	{
		symbol: 'FCT',
		name: 'Factom',
		color: '#417ba4',
		'Image Path': '/FormattedImages/FCT.png',
	},
	{
		symbol: 'FJC',
		name: 'Fujicoin',
		color: '#00afec',
		'Image Path': '/FormattedImages/FJC.png',
	},
	{
		symbol: 'FLDC',
		name: 'Foldingcoin',
		color: '#c40e09',
		'Image Path': '/FormattedImages/FLDC.png',
	},
	{
		symbol: 'FLO',
		name: 'FLO',
		color: '#2080a2',
		'Image Path': '/FormattedImages/FLO.png',
	},
	{
		symbol: 'FLUX',
		name: 'Flux',
		color: '#2b61d1',
		'Image Path': '/FormattedImages/FLUX.png',
	},
	{
		symbol: 'FSN',
		name: 'FUSION',
		color: '#1d9ad7',
		'Image Path': '/FormattedImages/FSN.png',
	},
	{
		symbol: 'FTC',
		name: 'Feathercoin',
		color: '#27323a',
		'Image Path': '/FormattedImages/FTC.png',
	},
	{
		symbol: 'FUN',
		name: 'FunFair',
		color: '#ed1968',
		'Image Path': '/FormattedImages/FUN.png',
	},
	{
		symbol: 'GIN',
		name: 'GINcoin',
		color: '#008dde',
		'Image Path': '/FormattedImages/GIN.png',
	},
	{
		symbol: 'GLXT',
		name: 'GLX Token',
		color: '#005396',
		'Image Path': '/FormattedImages/GLXT.png',
	},
	{
		symbol: 'GMR',
		name: 'Gimmer',
		color: '#372d2c',
		'Image Path': '/FormattedImages/GMR.png',
	},
	{
		symbol: 'GNO',
		name: 'Gnosis',
		color: '#00a6c4',
		'Image Path': '/FormattedImages/GNO.png',
	},
	{
		symbol: 'GRC',
		name: 'Gridcoin',
		color: '#5411b3',
		'Image Path': '/FormattedImages/GRC.png',
	},
	{
		symbol: 'GRIN',
		name: 'Grin',
		color: '#fff300',
		'Image Path': '/FormattedImages/GRIN.png',
	},
	{
		symbol: 'GRS',
		name: 'Groestlcoin',
		color: '#377e96',
		'Image Path': '/FormattedImages/GRS.png',
	},
	{
		symbol: 'GRT',
		name: 'The Graph',
		color: '#5942cc',
		'Image Path': '/FormattedImages/GRT.png',
	},
	{
		symbol: 'GSC',
		name: 'Global Social Chain',
		color: '#ff0060',
		'Image Path': '/FormattedImages/GSC.png',
	},
	{
		symbol: 'HIGHT',
		name: 'Highcoin',
		color: '#117fc0',
		'Image Path': '/FormattedImages/HIGHT.png',
	},
	{
		symbol: 'HNS',
		name: 'Handshake',
		color: '#000000',
		'Image Path': '/FormattedImages/HNS.png',
	},
	{
		symbol: 'HPB',
		name: 'High Performance Blockchain',
		color: '#1591ca',
		'Image Path': '/FormattedImages/HPB.png',
	},
	{
		symbol: 'HUSD',
		name: 'HUSD',
		color: '#005ffa',
		'Image Path': '/FormattedImages/HUSD.png',
	},
	{
		symbol: 'ICP',
		name: 'Internet Computer',
		color: '#292a2e',
		'Image Path': '/FormattedImages/ICP.png',
	},
	{
		symbol: 'ILK',
		name: 'Inlock Token',
		color: '#98c23a',
		'Image Path': '/FormattedImages/ILK.png',
	},
	{
		symbol: 'IOTX',
		name: 'IoTeX',
		color: '#00d4d5',
		'Image Path': '/FormattedImages/IOTX.png',
	},
	{
		symbol: 'ITC',
		name: 'IoT Chain',
		color: '#102044',
		'Image Path': '/FormattedImages/ITC.png',
	},
	{
		symbol: 'KIN',
		name: 'Kin',
		color: '#005fff',
		'Image Path': '/FormattedImages/KIN.png',
	},
	{
		symbol: 'KLOWN',
		name: 'Ether Clown',
		color: '#ea0017',
		'Image Path': '/FormattedImages/KLOWN.png',
	},
	{
		symbol: 'KNC',
		name: 'Kyber Network',
		color: '#31cb9e',
		'Image Path': '/FormattedImages/KNC.png',
	},
	{
		symbol: 'KSM',
		name: 'Kusama',
		color: '#000000',
		'Image Path': '/FormattedImages/KSM.png',
	},
	{
		symbol: 'LBC',
		name: 'LBRY Credits',
		color: '#006149',
		'Image Path': '/FormattedImages/LBC.png',
	},
	{
		symbol: 'LEO',
		name: 'Unus Sed LEO',
		color: '#11021e',
		'Image Path': '/FormattedImages/LEO.png',
	},
	{
		symbol: 'LINK',
		name: 'ChainLink',
		color: '#2a5ada',
		'Image Path': '/FormattedImages/LINK.png',
	},
	{
		symbol: 'LOOM',
		name: 'Loom Network',
		color: '#48beff',
		'Image Path': '/FormattedImages/LOOM.png',
	},
	{
		symbol: 'LSK',
		name: 'Lisk',
		color: '#0d4ea0',
		'Image Path': '/FormattedImages/LSK.png',
	},
	{
		symbol: 'LUN',
		name: 'Lunyr',
		color: '#f55749',
		'Image Path': '/FormattedImages/LUN.png',
	},
	{
		symbol: 'MAID',
		name: 'MaidSafeCoin',
		color: '#5592d7',
		'Image Path': '/FormattedImages/MAID.png',
	},
	{
		symbol: 'MANA',
		name: 'Decentraland',
		color: '#ff2d55',
		'Image Path': '/FormattedImages/MANA.png',
	},
	{
		symbol: 'MATIC',
		name: 'Polygon',
		color: '#6f41d8',
		'Image Path': '/FormattedImages/MATIC.png',
	},
	{
		symbol: 'MATIC',
		name: 'Polygon',
		color: '#6f41d8',
		'Image Path': '/FormattedImages/MATIC.png',
	},
	{
		symbol: 'MAX',
		name: 'MAX Token',
		color: '#2d4692',
		'Image Path': '/FormattedImages/MAX.png',
	},
	{
		symbol: 'MCO',
		name: 'Crypto.com',
		color: '#103f68',
		'Image Path': '/FormattedImages/MCO.png',
	},
	{
		symbol: 'MFT',
		name: 'Mainframe',
		color: '#da1157',
		'Image Path': '/FormattedImages/MFT.png',
	},
	{
		symbol: 'MITH',
		name: 'Mithril',
		color: '#00316d',
		'Image Path': '/FormattedImages/MITH.png',
	},
	{
		symbol: 'MKR',
		name: 'Maker',
		color: '#1aab9b',
		'Image Path': '/FormattedImages/MKR.png',
	},
	{
		symbol: 'MNZ',
		name: 'MNZ',
		color: '#7f368a',
		'Image Path': '/FormattedImages/MNZ.png',
	},
	{
		symbol: 'MSR',
		name: 'Masari',
		color: '#47b95c',
		'Image Path': '/FormattedImages/MSR.png',
	},
	{
		symbol: 'MTH',
		name: 'Monetha',
		color: '#104fca',
		'Image Path': '/FormattedImages/MTH.png',
	},
	{
		symbol: 'MUSIC',
		name: 'Musicoin',
		color: '#ffffff',
		'Image Path': '/FormattedImages/MUSIC.png',
	},
	{
		symbol: 'MZC',
		name: 'MAZA',
		color: '#ffaa05',
		'Image Path': '/FormattedImages/MZC.png',
	},
	{
		symbol: 'NCASH',
		name: 'Nucleus Vision',
		color: '#36a9cf',
		'Image Path': '/FormattedImages/NCASH.png',
	},
	{
		symbol: 'NEU',
		name: 'Neumark',
		color: '#b3ba00',
		'Image Path': '/FormattedImages/NEU.png',
	},
	{
		symbol: 'NEXO',
		name: 'Nexo',
		color: '#1a4199',
		'Image Path': '/FormattedImages/NEXO.png',
	},
	{
		symbol: 'NKN',
		name: 'NKN',
		color: '#23336f',
		'Image Path': '/FormattedImages/NKN.png',
	},
	{
		symbol: 'NLC2',
		name: 'NoLimitCoin',
		color: '#f28f01',
		'Image Path': '/FormattedImages/NLC2.png',
	},
	{
		symbol: 'NMR',
		name: 'Numeraire',
		color: '#050708',
		'Image Path': '/FormattedImages/NMR.png',
	},
	{
		symbol: 'NPXS',
		name: 'Pundi X',
		color: '#f5d100',
		'Image Path': '/FormattedImages/NPXS.png',
	},
	{
		symbol: 'NTBC',
		name: 'Note Blockchain',
		color: '#eec315',
		'Image Path': '/FormattedImages/NTBC.png',
	},
	{
		symbol: 'NXS',
		name: 'Nexus',
		color: '#4099cd',
		'Image Path': '/FormattedImages/NXS.png',
	},
	{
		symbol: 'OAX',
		name: 'OpenANX',
		color: '#164b79',
		'Image Path': '/FormattedImages/OAX.png',
	},
	{
		symbol: 'OMG',
		name: 'OMG Network',
		color: '#101010',
		'Image Path': '/FormattedImages/OMG.png',
	},
	{
		symbol: 'ONE',
		name: 'Harmony',
		color: '#00aee9',
		'Image Path': '/FormattedImages/ONE.png',
	},
	{
		symbol: 'OOT',
		name: 'Utrum',
		color: '#25aae1',
		'Image Path': '/FormattedImages/OOT.png',
	},
	{
		symbol: 'OXT',
		name: 'Orchid',
		color: '#5f45ba',
		'Image Path': '/FormattedImages/OXT.png',
	},
	{
		symbol: 'PART',
		name: 'Particl',
		color: '#65cb8d',
		'Image Path': '/FormattedImages/PART.png',
	},
	{
		symbol: 'PAX',
		name: 'PAX Token',
		color: '#398260',
		'Image Path': '/FormattedImages/PAX.png',
	},
	{
		symbol: 'PAXG',
		name: 'PAX Gold',
		color: '#e4ce4d',
		'Image Path': '/FormattedImages/PAXG.png',
	},
	{
		symbol: 'PAY',
		name: 'TenX',
		color: '#302c2c',
		'Image Path': '/FormattedImages/PAY.png',
	},
	{
		symbol: 'POWR',
		name: 'Power Ledger',
		color: '#05bca9',
		'Image Path': '/FormattedImages/POWR.png',
	},
	{
		symbol: 'PPP',
		name: 'PayPie',
		color: '#348f8d',
		'Image Path': '/FormattedImages/PPP.png',
	},
	{
		symbol: 'PRL',
		name: 'Oyster',
		color: '#1061e3',
		'Image Path': '/FormattedImages/PRL.png',
	},
	{
		symbol: 'PUNGO',
		name: 'Pungo Token',
		color: '#22b573',
		'Image Path': '/FormattedImages/PUNGO.png',
	},
	{
		symbol: 'QASH',
		name: 'QASH',
		color: '#1347e8',
		'Image Path': '/FormattedImages/QASH.png',
	},
	{
		symbol: 'QIWI',
		name: 'QIWI',
		color: '#ff8c00',
		'Image Path': '/FormattedImages/QIWI.png',
	},
	{
		symbol: 'QLC',
		name: 'QLC Chain',
		color: '#610089',
		'Image Path': '/FormattedImages/QLC.png',
	},
	{
		symbol: 'QTUM',
		name: 'Qtum',
		color: '#2e9ad0',
		'Image Path': '/FormattedImages/QTUM.png',
	},
	{
		symbol: 'RCN',
		name: 'Rcoin',
		color: '#3555f9',
		'Image Path': '/FormattedImages/RCN.png',
	},
	{
		symbol: 'RDD',
		name: 'Reddcoin',
		color: '#e30613',
		'Image Path': '/FormattedImages/RDD.png',
	},
	{
		symbol: 'REN',
		name: 'Ren',
		color: '#080817',
		'Image Path': '/FormattedImages/REN.png',
	},
	{
		symbol: 'REP',
		name: 'Augur',
		color: '#602a52',
		'Image Path': '/FormattedImages/REP.png',
	},
	{
		symbol: 'REPV2',
		name: 'Augur',
		color: '#0e0e21',
		'Image Path': '/FormattedImages/REPV2.png',
	},
	{
		symbol: 'REQ',
		name: 'Request',
		color: '#00e6a0',
		'Image Path': '/FormattedImages/REQ.png',
	},
	{
		symbol: 'RLC',
		name: 'iExec RLC',
		color: '#ffd800',
		'Image Path': '/FormattedImages/RLC.png',
	},
	{
		symbol: 'RPX',
		name: 'RPX',
		color: '#8d181b',
		'Image Path': '/FormattedImages/RPX.png',
	},
	{
		symbol: 'RVN',
		name: 'Ravencoin',
		color: '#384182',
		'Image Path': '/FormattedImages/RVN.png',
	},
	{
		symbol: 'SAFE',
		name: 'Safe',
		color: '#00688c',
		'Image Path': '/FormattedImages/SAFE.png',
	},
	{
		symbol: 'SAFEMOON',
		name: 'SafeMoon',
		color: '#00a79d',
		'Image Path': '/FormattedImages/SAFEMOON.png',
	},
	{
		symbol: 'SAI',
		name: 'Single Collateral DAI',
		color: '#b68900',
		'Image Path': '/FormattedImages/SAI.png',
	},
	{
		symbol: 'SAN',
		name: 'Santiment Network Token',
		color: '#2b77b3',
		'Image Path': '/FormattedImages/SAN.png',
	},
	{
		symbol: 'SAND',
		name: 'The Sandbox',
		color: '#04adef',
		'Image Path': '/FormattedImages/SAND.png',
	},
	{
		symbol: 'SBERBANK',
		name: 'SBERBANK',
		color: '#48b254',
		'Image Path': '/FormattedImages/SBERBANK.png',
	},
	{
		symbol: 'SIN',
		name: 'SINOVATE',
		color: '#f5342e',
		'Image Path': '/FormattedImages/SIN.png',
	},
	{
		symbol: 'SKL',
		name: 'SKALE Network',
		color: '#000000',
		'Image Path': '/FormattedImages/SKL.png',
	},
	{
		symbol: 'SKY',
		name: 'Skycoin',
		color: '#0072ff',
		'Image Path': '/FormattedImages/SKY.png',
	},
	{
		symbol: 'SLR',
		name: 'Solarcoin',
		color: '#fda616',
		'Image Path': '/FormattedImages/SLR.png',
	},
	{
		symbol: 'SNGLS',
		name: 'SingularDTV',
		color: '#b30d23',
		'Image Path': '/FormattedImages/SNGLS.png',
	},
	{
		symbol: 'SNM',
		name: 'SONM',
		color: '#0b1c26',
		'Image Path': '/FormattedImages/SNM.png',
	},
	{
		symbol: 'SNX',
		name: 'Synthetix',
		color: '#5fcdf9',
		'Image Path': '/FormattedImages/SNX.png',
	},
	{
		symbol: 'SOC',
		name: 'All Sports',
		color: '#199248',
		'Image Path': '/FormattedImages/SOC.png',
	},
	{
		symbol: 'SOL',
		name: 'Solana',
		color: '#66f9a1',
		'Image Path': '/FormattedImages/SOL.png',
	},
	{
		symbol: 'SPACEHBIT',
		name: 'HashBit Blockchain',
		color: '#0971fe',
		'Image Path': '/FormattedImages/SPACEHBIT.png',
	},
	{
		symbol: 'SPANK',
		name: 'SpankChain',
		color: '#ff3b81',
		'Image Path': '/FormattedImages/SPANK.png',
	},
	{
		symbol: 'SPHTX',
		name: 'SophiaTX',
		color: '#00b098',
		'Image Path': '/FormattedImages/SPHTX.png',
	},
	{
		symbol: 'STORJ',
		name: 'Storj',
		color: '#2683ff',
		'Image Path': '/FormattedImages/STORJ.png',
	},
	{
		symbol: 'STOX',
		name: 'Stox',
		color: '#7324f0',
		'Image Path': '/FormattedImages/STOX.png',
	},
	{
		symbol: 'STRAT',
		name: 'Stratis',
		color: '#1387c9',
		'Image Path': '/FormattedImages/STRAT.png',
	},
	{
		symbol: 'STX',
		name: 'Stacks',
		color: '#5546ff',
		'Image Path': '/FormattedImages/STX.png',
	},
	{
		symbol: 'SUSHI',
		name: 'SushiSwap',
		color: '#d65892',
		'Image Path': '/FormattedImages/SUSHI.png',
	},
	{
		symbol: 'SYS',
		name: 'Syscoin',
		color: '#0082c6',
		'Image Path': '/FormattedImages/SYS.png',
	},
	{
		symbol: 'TBX',
		name: 'Tokenbox',
		color: '#5244d4',
		'Image Path': '/FormattedImages/TBX.png',
	},
	{
		symbol: 'TEN',
		name: 'Tokenomy',
		color: '#0899cd',
		'Image Path': '/FormattedImages/TEN.png',
	},
	{
		symbol: 'TGCH',
		name: 'TrueGalaxyCash',
		color: '#434247',
		'Image Path': '/FormattedImages/TGCH.png',
	},
	{
		symbol: 'TKS',
		name: 'Tokes Platform',
		color: '#895af8',
		'Image Path': '/FormattedImages/TKS.png',
	},
	{
		symbol: 'TOMO',
		name: 'TomoChain',
		color: '#1a1f36',
		'Image Path': '/FormattedImages/TOMO.png',
	},
	{
		symbol: 'TPAY',
		name: 'TokenPay',
		color: '#3058a6',
		'Image Path': '/FormattedImages/TPAY.png',
	},
	{
		symbol: 'TRIG',
		name: 'Triggers',
		color: '#30c0f2',
		'Image Path': '/FormattedImages/TRIG.png',
	},
	{
		symbol: 'TRTL',
		name: 'TurtleCoin',
		color: '#00843d',
		'Image Path': '/FormattedImages/TRTL.png',
	},
	{
		symbol: 'TRX',
		name: 'TRON',
		color: '#ef0027',
		'Image Path': '/FormattedImages/TRX.png',
	},
	{
		symbol: 'TUSD',
		name: 'TrueUSD',
		color: '#2b2e7f',
		'Image Path': '/FormattedImages/TUSD.png',
	},
	{
		symbol: 'UBQ',
		name: 'Ubiq',
		color: '#00ea90',
		'Image Path': '/FormattedImages/UBQ.png',
	},
	{
		symbol: 'UMA',
		name: 'UMA',
		color: '#ff4a4a',
		'Image Path': '/FormattedImages/UMA.png',
	},
	{
		symbol: 'UNI',
		name: 'Uniswap',
		color: '#ff007a',
		'Image Path': '/FormattedImages/UNI.png',
	},
	{
		symbol: 'USDC',
		name: 'USD Coin',
		color: '#3e73c4',
		'Image Path': '/FormattedImages/USDC.png',
	},
	{
		symbol: 'VIBE',
		name: 'VIBE',
		color: '#338be5',
		'Image Path': '/FormattedImages/VIBE.png',
	},
	{
		symbol: 'VRSC',
		name: 'VerusCoin',
		color: '#3165d4',
		'Image Path': '/FormattedImages/VRSC.png',
	},
	{
		symbol: 'VRSC',
		name: 'VerusCoin',
		color: '#3165d4',
		'Image Path': '/FormattedImages/VRSC.png',
	},
	{
		symbol: 'VTC',
		name: 'Vertcoin',
		color: '#048657',
		'Image Path': '/FormattedImages/VTC.png',
	},
	{
		symbol: 'WABI',
		name: 'Tael',
		color: '#399b32',
		'Image Path': '/FormattedImages/WABI.png',
	},
	{
		symbol: 'WAN',
		name: 'Wanchain',
		color: '#136aad',
		'Image Path': '/FormattedImages/WAN.png',
	},
	{
		symbol: 'WBTC',
		name: 'Wrapped Bitcoin',
		color: '#201a2d',
		'Image Path': '/FormattedImages/WBTC.png',
	},
	{
		symbol: 'WICC',
		name: 'WaykiChain',
		color: '#5783cb',
		'Image Path': '/FormattedImages/WICC.png',
	},
	{
		symbol: 'WINGS',
		name: 'Wings',
		color: '#0dc9f7',
		'Image Path': '/FormattedImages/WINGS.png',
	},
	{
		symbol: 'WPR',
		name: 'WePower',
		color: '#ffe600',
		'Image Path': '/FormattedImages/WPR.png',
	},
	{
		symbol: 'XAS',
		name: 'Asch',
		color: '#faa00d',
		'Image Path': '/FormattedImages/XAS.png',
	},
	{
		symbol: 'XBC',
		name: 'Bitcoin Plus',
		color: '#f7931a',
		'Image Path': '/FormattedImages/XBC.png',
	},
	{
		symbol: 'XBP',
		name: 'BlitzPredict',
		color: '#21af67',
		'Image Path': '/FormattedImages/XBP.png',
	},
	{
		symbol: 'XMCC',
		name: 'Monoeci',
		color: '#dd0632',
		'Image Path': '/FormattedImages/XMCC.png',
	},
	{
		symbol: 'XP',
		name: 'XP',
		color: '#008200',
		'Image Path': '/FormattedImages/XP.png',
	},
	{
		symbol: 'XPR',
		name: 'Proton',
		color: '#7543e3',
		'Image Path': '/FormattedImages/XPR.png',
	},
	{
		symbol: 'XSG',
		name: 'SnowGem',
		color: '#d21e2b',
		'Image Path': '/FormattedImages/XSG.png',
	},
	{
		symbol: 'XVG',
		name: 'Verge',
		color: '#00cbff',
		'Image Path': '/FormattedImages/XVG.png',
	},
	{
		symbol: 'YFI',
		name: 'yearn.finance',
		color: '#006ae3',
		'Image Path': '/FormattedImages/YFI.png',
	},
	{
		symbol: 'ZCL',
		name: 'Zclassic',
		color: '#c87035',
		'Image Path': '/FormattedImages/ZCL.png',
	},
	{
		symbol: 'ZEN',
		name: 'Horizen',
		color: '#00eaab',
		'Image Path': '/FormattedImages/ZEN.png',
	},
	{
		symbol: 'ZEST',
		name: 'Zest',
		color: '#07bc9c',
		'Image Path': '/FormattedImages/ZEST.png',
	},
	{
		symbol: 'ZEST',
		name: 'Zest',
		color: '#07bc9c',
		'Image Path': '/FormattedImages/ZEST.png',
	},
	{
		symbol: 'ZILLA',
		name: 'Chainzilla',
		color: '#00004d',
		'Image Path': '/FormattedImages/ZILLA.png',
	},
	{
		symbol: 'ZRX',
		name: '0x',
		color: '#302c2c',
		'Image Path': '/FormattedImages/ZRX.png',
	},
];
